#server.port: 8090

server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: jks
    key-alias: tomcat
    key-password: password
  port: 9443


logging.level:
  com.prapps: DEBUG
  org.springframework:
    web:
      #servlet: DEBUG
      socket.messaging: ERROR
    messaging: ERROR
